namespace: ci-cd
image_stream_namespace: openshift

build_vars:
  IMAGE_STREAM_NAMESPACE: "{{ image_stream_namespace }}"
  PROMETHEUS_AGENT_VERSION: 0.12.0
  AMQ_IMAGE_STREAM: amq-broker:7.4

openshift_cluster_content:
- object: Builds
  content:
  - name: AMQ Broker Prometheus image build
    template: "{{ inventory_dir }}/templates/build.yml"
    params_from_vars: "{{ build_vars }}"
    namespace: "{{ namespace }}"
    tags:
    - build
    - amq
